In [1]:
def describe(x):
  print("Type:{}".format(x.type))
  print("Shape:{}".format(x.shape))
  print("Values:{}".format(x))

In [2]:
import torch

describe(torch.Tensor(2,3))

Type:<built-in method type of Tensor object at 0x104210c18>
Shape:torch.Size([2, 3])
Values:tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
import torch
describe(torch.rand(2,3))


Type:<built-in method type of Tensor object at 0x1097e6e10>
Shape:torch.Size([2, 3])
Values:tensor([[0.5345, 0.4024, 0.7073],
        [0.4410, 0.6246, 0.6358]])


In [4]:
describe(torch.randn(2,3))

Type:<built-in method type of Tensor object at 0x1098215e8>
Shape:torch.Size([2, 3])
Values:tensor([[-0.5451, -0.5908, -0.8417],
        [-0.7174, -2.3215,  1.8876]])


In [5]:
import torch 
describe(torch.zeros(2,3))

Type:<built-in method type of Tensor object at 0x1098218b8>
Shape:torch.Size([2, 3])
Values:tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.ones(2,3)

In [7]:
describe(x)

Type:<built-in method type of Tensor object at 0x109821c18>
Shape:torch.Size([2, 3])
Values:tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x.fill_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [9]:
describe(x)

Type:<built-in method type of Tensor object at 0x109821c18>
Shape:torch.Size([2, 3])
Values:tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [12]:
x = torch.Tensor([[1,2,3],[4,5,6]])

In [14]:
describe(x)

Type:<built-in method type of Tensor object at 0x109821438>
Shape:torch.Size([2, 3])
Values:tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [15]:
import torch 
import numpy as np
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type:<built-in method type of Tensor object at 0x1041ff4c8>
Shape:torch.Size([2, 3])
Values:tensor([[0.6526, 0.9408, 0.4779],
        [0.6961, 0.4401, 0.4394]], dtype=torch.float64)


##### Tensor Types and Size

In [16]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])

In [17]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [18]:
x = x.long()

In [19]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
x = x.float()

In [22]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

##### Tensor Operations

In [23]:
import torch 
x = torch.randn(2,3)

In [25]:
describe(x)

Type:<built-in method type of Tensor object at 0x1042101b0>
Shape:torch.Size([2, 3])
Values:tensor([[-0.1915, -1.5938, -0.7892],
        [-0.6004,  1.0347,  0.3203]])


In [28]:
describe(torch.add(x,x))

Type:<built-in method type of Tensor object at 0x11efc94c8>
Shape:torch.Size([2, 3])
Values:tensor([[-0.3829, -3.1876, -1.5785],
        [-1.2009,  2.0694,  0.6406]])


In [29]:
describe(x+x)

Type:<built-in method type of Tensor object at 0x11efc9948>
Shape:torch.Size([2, 3])
Values:tensor([[-0.3829, -3.1876, -1.5785],
        [-1.2009,  2.0694,  0.6406]])


## Example 1-10

In [32]:
import torch
x = torch.arange(6)
describe(x)

Type:<built-in method type of Tensor object at 0x11efcf360>
Shape:torch.Size([6])
Values:tensor([0, 1, 2, 3, 4, 5])


In [33]:
x = x.view(2,3)

In [34]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [35]:
describe(torch.sum(x,dim=0))

Type:<built-in method type of Tensor object at 0x11efcf9d8>
Shape:torch.Size([3])
Values:tensor([3, 5, 7])


In [36]:
describe(torch.sum(x,dim=1))

Type:<built-in method type of Tensor object at 0x11efcfc18>
Shape:torch.Size([2])
Values:tensor([ 3, 12])


### Indexing, Slicing and Joining

In [37]:
import torch
x = torch.arange(6).view(2,3)

In [38]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [39]:
describe(x[:1,:2])

Type:<built-in method type of Tensor object at 0x11efda4c8>
Shape:torch.Size([1, 2])
Values:tensor([[0, 1]])


In [40]:
describe(x[0,1])

Type:<built-in method type of Tensor object at 0x11efda798>
Shape:torch.Size([])
Values:1


##### Example 1-12

In [42]:
indeces = torch.LongTensor([0,2])

In [43]:
indeces

tensor([0, 2])

In [44]:
indices = torch.LongTensor([0,0])

In [52]:
torch.arange(1).long()

tensor([0])

##### Example 1-16

In [54]:
import torch
print(torch.cuda.is_available())

False


In [55]:
import spacy


In [56]:
nlp = spacy.load('en')

In [58]:
text = "Mary, don't slap the green witch"

print([str(token) for token >in nlp(text.lower())])

SyntaxError: invalid syntax (<ipython-input-58-283fce6d2097>, line 3)

In [59]:
from nltk.tokenize import TweetTokenizer
tweet="Snow White and the Seven Degre"
tokenizer = TweetTokenizer()

print(tokenizer.tokenize(tweet.lower()))

['snow', 'white', 'and', 'the', 'seven', 'degre']


##### Lemmatization

In [64]:
import spacy
nlp = spacy.load('en')
doc= nlp("he was runing late")

In [66]:
for token in doc:
    print('{}--{}'.format(token,token.lemma_))

he---PRON-
was--be
runing--run
late--late


In [67]:
import spacy
nlp = spacy.load('en')
doc = nlp("Mary slapped the green witch")

for token in doc:
    print('{} - {}'.format(token,token.pos_))

Mary - PROPN
slapped - VERB
the - DET
green - ADJ
witch - NOUN


In [68]:
import spacy
nlp = spacy.load('en')

doc = nlp('Mary slapped the green witch')

for chunk in doc.noun_chunks:
    print("{} - {}".format(chunk,chunk.label_))

Mary - NP
the green witch - NP


##### Example 3.1

In [70]:
import torch
import torch.nn as nn

class Perceptron(nn.Module):
    def __init__(self,input_dim):
        super(Perceptron,self).__init__()
        self.fc1 = nn.Linear(input_dim,1)
        
    def forward(self,x_in):
        return torch.sigmodi(self.fc1(x_in)).squeeze()